incr14 check
lekan-pvp/go-musthave-shortener-tpl pull request #14
Opened 2022-01-12 20:02 UTC by lekan-pvp

2022-01-24 19:00 UTC, Perederey requested changes
В целом все отлично!
Я вижу хорошую работу, но в тоже время, я вижу, какие вещи можно еще улучшишь и ты точно с этим справишься

1) Переделать fanIn/fanOut и сделать worker, который будет слушать сообщения (закрепить каналы)
2) Небольшой рефакторинг по комментам
3) Поправить go vet (без него не могу принять PR)

2022-01-24 19:00 UTC, Perederey commented on cmd/shortener/main.go
>  package main
надо обязательно поправить go vet, он ругается на несколько вещей у тебя (кроме body Close)

```
11
internal/cookie_handler/cookie_handler.go:1:1: should not use underscores in package names
12
# github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/key_gen
13
internal/key_gen/key_gen.go:1:1: should not use underscores in package names
14
internal/key_gen/key_gen.go:28:44: func parameter userId should be userID
15
# github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/repository-db
16
internal/repository-db/repository-db.go:1:1: should not use underscores in package names
17
internal/repository-db/repository-db.go:139:24: method BanchApiRepo should be BanchAPIRepo
18
internal/repository-db/repository-db.go:11:2: package "github.com/lib/pq" is being imported more than once
19
# github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/service-memory
20
internal/service-memory/serviceMemory.go:1:1: should not use underscores in package names
21
internal/service-memory/serviceMemory.go:33:25: method BanchApi should be BanchAPI
22
# github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/repository-memory
23
internal/repository-memory/repository-memory.go:1:1: should not use underscores in package names
24
internal/repository-memory/repository-memory.go:115:28: method BanchApiRepo should be BanchAPIRepo
25
# github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/server
26
internal/server/server.go:24:14: github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/service-memory.Service composite literal uses unkeyed fields
27
internal/server/server.go:25:16: github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/controllers.Controller composite literal uses unkeyed fields
28
# github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/generate_random
29
internal/generate_random/generate_random.go:1:1: should not use underscores in package names
30
# github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/service-db
31
internal/service-db/serviceDB.go:1:1: should not use underscores in package names
32
internal/service-db/serviceDB.go:45:25: method BanchApi should be BanchAPI
33
# github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/test_helper
34
internal/test_helper/test_request.go:1:1: should not use underscores in package names
35
# github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/controllers
36
internal/controllers/add_short_url_test.go:22:39: response body must be closed
37
internal/controllers/add_short_url_test.go:26:38: response body must be closed
38
internal/controllers/add_short_url_test.go:30:38: response body must be closed
39
internal/controllers/add_short_url_test.go:34:38: response body must be closed
40
internal/controllers/api_shorten_test.go:41:38: response body must be closed
41
internal/controllers/api_shorten_test.go:45:38: response body must be closed
42
internal/controllers/api_shorten_test.go:49:38: response body must be closed
43
internal/controllers/api_shorten_test.go:55:36: response body must be closed
44
internal/controllers/get_url_by_id_test.go:28:38: response body must be closed
45
internal/controllers/get_url_by_id_test.go:32:38: response body must be closed
46
internal/controllers/get_url_by_id_test.go:36:38: response body must be closed
47
internal/controllers/get_url_by_id_test.go:40:39: response body must be closed
48
internal/controllers/api_shorten.go:20:2: struct field Url should be URL
49
internal/controllers/api_shorten.go:57:2: var shortUrl should be shortURL
50
internal/controllers/batch_handler.go:12:31: method ApiShortenBatch should be APIShortenBatch
```

2022-01-24 19:00 UTC, Perederey commented on cmd/shortener/main.go
> +import "github.com/lekan-pvp/go-musthave-shortener-tpl.git/internal/server"
обычно git не добавляются к названию папки, но это незначительно

2022-01-24 19:00 UTC, Perederey commented on internal/controllers/delete_handler.go
> +//
не понял, а почему ты этот файл просто не удалил?

2022-01-24 19:00 UTC, Perederey commented on internal/controllers/get_url_by_id.go
> +	if orig != "deleted" {
чтобы избегать всяких опечаток, лучше возвращать orig как структуру

```go
// OriginLink ...
type OriginLink struct {
    Link string
    Deleted bool
}

func (l OriginLink) IsDeleted() {
    return l.deleted == true
}
```

2022-01-24 19:00 UTC, Perederey commented on internal/controllers/get_url_by_id.go
> +		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
а разве мы дальше не json везде используем?

2022-01-24 19:00 UTC, Perederey commented on internal/controllers/get_url_by_id.go
> +		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
2) задачка на усложнение
попробуй сделать установку повторяющихся хедеров через  паттерн middleware, чтобы сократить количество кода
То есть ты только в одном месте прописываешь заголовки, а функцией middleware управляешь заголовки.

2022-01-24 19:00 UTC, Perederey commented on internal/controllers/udate_handler.go
> +	values := strings.Split(cookie.Value, ":")
лучше бы вынести это дело в validator или CookeParser

и лучше проверка куки до его установки?

2022-01-24 19:00 UTC, Perederey commented on internal/controllers/udate_handler.go
> +	body, err := io.ReadAll(r.Body)
забыл закрыть `defer body.Close()`

2022-01-24 19:00 UTC, Perederey commented on internal/controllers/udate_handler.go
> +	err = json.Unmarshal(body, &in)
Лучше структуру для unmarshalling указывать возле json, если мне память не изменяет она создаться все равно при запуске, а тебе будет нагляднее
и для таких операций можно использовать "короткую" запись 
```go
var links []string
if err := json.Unmarshal(body, &links); err != nil {
    // err
}
```

2022-01-24 19:00 UTC, Perederey commented on internal/controllers/udate_handler.go
> +	err = controller.UpdateURLs(r.Context(), uuid, in)
тут мы говорили переименовать лучше контроллер в service

2022-01-24 19:00 UTC, Perederey commented on internal/repository-db/repository-db.go
> +	result, err := db.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS users(id SERIAL, user_id VARCHAR, short_url VARCHAR NOT NULL, orig_url VARCHAR NOT NULL, correlation_id VARCHAR, is_deleted VARCHAR(10)
давай вынесем эту штуку в отдельное cli приложение и ты будешь его запускать перед стартом тестов. Сможешь сделать?

2022-01-24 19:00 UTC, Perederey commented on internal/repository-db/repository-db.go
> +	err := db.QueryRowContext(ctx2, `SELECT orig_url, is_deleted FROM users WHERE short_url=$1;`, shortURL).Scan(&result, &deleted)
ctx - должен остаться

2022-01-24 19:00 UTC, Perederey commented on internal/repository-db/repository-db.go
> +	if deleted == "deleted" {
я уже говорил немного выше про модель, еще тут у тебя путаница того, что одно и тоже поле используется для разных целей (для хранения и для управления)

и поэтому у тебя в будущем возникнет много проблем

1) в одно месте не обработаешь ошибку и API будет возвращать deleted, вместо пустой ссылки
2) появится еще один метод и (какой-нибудь hard-delete), и уже логика станет сложно поддерживаемой

2022-01-24 19:00 UTC, Perederey commented on internal/repository-db/repository-db.go
> +	fanOutChs := fanOut(shortBases, n)
а сможешь сделать fanIn и FanOut в разных местах? Чтобы fainOut читал воркер, который ты также запустишь при старте вместе с севером?

2022-01-24 19:00 UTC, Perederey commented on internal/repository-db/repository-db.go
> +	if db == nil {
подумай, как можно сделать так, чтобы эту ошибку не проверять каждый раз?

2022-01-24 19:00 UTC, Perederey commented on internal/repository-db/repository-db.go
> +	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
почему бы управление context не отдать сервису (контроллеру)?

2022-01-24 19:45 UTC, lekan-pvp commented on internal/controllers/get_url_by_id.go
> +		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
предыдущие тесты не пройдут. этот хендлер из ранних инкрементов

2022-01-25 19:45 UTC, lekan-pvp commented on internal/repository-db/repository-db.go
> +	result, err := db.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS users(id SERIAL, user_id VARCHAR, short_url VARCHAR NOT NULL, orig_url VARCHAR NOT NULL, correlation_id VARCHAR, is_deleted VARCHAR(10)
вот здесь не понял что именно вынести и как запустить перед стартом тестов. Надо разобраться

2022-01-25 20:04 UTC, lekan-pvp commented
исправил не прям все, некоторые моменты не до конца понятны, поэтому не стал рисковать. Но основное сделал. Просто завтра открытие 5,6 спринта. Боюсь сейчас закопаюсь и время потеряю. Я ведь еще не знаю что меня ждет))

2022-01-31 19:02 UTC, merged